name: Continuous Development Release

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  create-or-update-dev-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish Windows Executable
      run: |
        dotnet publish -c Release -r win-x64 --self-contained true \
        -p:PublishSingleFile=true \
        -p:EnableCompressionInSingleFile=true \
        -o ./bin/Release/publish_windows-x64
        cd ./bin/Release/publish_windows-x64
        zip -r ../publish_windows.zip *
        cd ../../../

    - name: Publish Linux Executable
      run: |
        dotnet publish -c Release -r linux-x64 --self-contained true \
        -p:PublishSingleFile=true \
        -p:EnableCompressionInSingleFile=true \
        -o ./bin/Release/publish_linux-x64
        cd ./bin/Release/publish_linux-x64
        zip -r ../publish_linux.zip *
        cd ../../../

    - name: Get the latest release
      id: get_latest_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        latest_release=$(gh release list --limit 1 --json tagName --jq '.[0].tagName' | grep -Eo '[0-9]+\.[0-9]+' || echo "0.0")
        echo "latest_release=$latest_release" >> $GITHUB_ENV

    - name: Increment version
      id: increment_version
      run: |
        current_version=${{ env.latest_release }}
        major=$(echo $current_version | cut -d. -f1)
        minor=$(echo $current_version | cut -d. -f2)
        new_version="$major.$((minor+1))"
        echo "new_version=$new_version" >> $GITHUB_ENV

    - name: Create or Update Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Get the current date
        DATE=$(date +'%Y%m%d')

        # Set the release title and tag name
        RELEASE_TITLE="Development Release v${{ env.new_version }}"
        TAG_NAME="dev_${DATE}_v${{ env.new_version }}"

        # Check if the release already exists
        release_exists=$(gh release list --limit 1 --json tagName --jq '.[0].tagName' | grep -E "^$TAG_NAME$" || echo "no")

        # Create or update the release using the GitHub CLI
        if [ "$release_exists" = "no" ]; then
          gh release create "$TAG_NAME" ./bin/Release/publish_windows.zip ./bin/Release/publish_linux.zip --title "$RELEASE_TITLE" --target dev
        else
          gh release upload "$TAG_NAME" ./bin/Release/publish_windows.zip ./bin/Release/publish_linux.zip --clobber
        fi