name: .NET Publish and Release

on:
  push:
    tags:
      - 'dev*' # Trigger on version tags

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x' # Adjust to your project's .NET version
    
    - name: Publish Linux Artifact
      run: |
        # Publish for Linux
        dotnet publish -c Release -r linux-x64 --self-contained true -o ./bin/Release/publish_linux-x64
        
        # Zip Linux artifacts
        cd ./bin/Release/publish_linux-x64
        zip -r ../publish_linux.zip *
        cd ../../../
    
    - name: Publish Windows Artifact
      run: |
        # Publish for Windows
        dotnet publish -c Release -r win-x64 --self-contained true -o ./bin/Release/publish_windows-x64
        
        # Zip Windows artifacts
        cd ./bin/Release/publish_windows-x64
        zip -r ../publish_windows.zip *
        cd ../../../
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./bin/Release/publish_linux.zip
          ./bin/Release/publish_windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
