name: .NET Cross-Platform Release

on:
  push:
    tags:
      - 'dev*' # Triggers on version tags like v1.0.0

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Adjust to your project's .NET version
    
    - name: Publish Windows Executable
      run: |
        # Publish Windows x64 executable
        dotnet publish -c Release -r win-x64 --self-contained true \
        -p:PublishSingleFile=true \
        -p:EnableCompressionInSingleFile=true \
        -p:PublishReadyToRun=true \
        -o ./bin/Release/publish_windows-x64
        
        # Zip Windows artifacts
        cd ./bin/Release/publish_windows-x64
        zip -r ../publish_windows.zip *
        cd ../../../
    
    - name: Publish Linux Executable
      run: |
        # Publish Linux x64 executable
        dotnet publish -c Release -r linux-x64 --self-contained true \
        -p:PublishSingleFile=true \
        -p:EnableCompressionInSingleFile=true \
        -o ./bin/Release/publish_linux-x64
        
        # Zip Linux artifacts
        cd ./bin/Release/publish_linux-x64
        zip -r ../publish_linux.zip *
        cd ../../../
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./bin/Release/publish_windows.zip
          ./bin/Release/publish_linux.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
